# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.srcs/sources_1/ip/wave_delay_fifo/wave_delay_fifo.xci
# IP: The module: 'wave_delay_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.gen/sources_1/ip/wave_delay_fifo/wave_delay_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'wave_delay_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.gen/sources_1/ip/wave_delay_fifo/wave_delay_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wave_delay_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.srcs/sources_1/ip/wave_delay_fifo/wave_delay_fifo.xci
# IP: The module: 'wave_delay_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.gen/sources_1/ip/wave_delay_fifo/wave_delay_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'wave_delay_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.gen/sources_1/ip/wave_delay_fifo/wave_delay_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wave_delay_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
