@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Jul 12 23:08:34 -0400 2026
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM simulate design
echo "xsim tb_phase_accumulator_behav -key {Behavioral:sim_1:Functional:tb_phase_accumulator} -tclbatch tb_phase_accumulator.tcl -protoinst "protoinst_files/bd_757b.protoinst" -protoinst "protoinst_files/bd_b546.protoinst" -protoinst "protoinst_files/full_design.protoinst" -log simulate.log"
call xsim  tb_phase_accumulator_behav -key {Behavioral:sim_1:Functional:tb_phase_accumulator} -tclbatch tb_phase_accumulator.tcl -protoinst "protoinst_files/bd_757b.protoinst" -protoinst "protoinst_files/bd_b546.protoinst" -protoinst "protoinst_files/full_design.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
