# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.srcs/sources_1/ip/dac_driver/dac_driver.xci
# IP: The module: 'dac_driver' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.gen/sources_1/ip/dac_driver/dac_driver_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_driver'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.gen/sources_1/ip/dac_driver/dac_driver.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_driver'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.srcs/sources_1/ip/dac_driver/dac_driver.xci
# IP: The module: 'dac_driver' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.gen/sources_1/ip/dac_driver/dac_driver_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_driver'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.gen/sources_1/ip/dac_driver/dac_driver.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_driver'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
