# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.srcs/sources_1/ip/DAC_Driver/DAC_Driver.xci
# IP: The module: 'DAC_Driver' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.gen/sources_1/ip/DAC_Driver/DAC_Driver_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAC_Driver'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.gen/sources_1/ip/DAC_Driver/DAC_Driver.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAC_Driver'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.srcs/sources_1/ip/DAC_Driver/DAC_Driver.xci
# IP: The module: 'DAC_Driver' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.gen/sources_1/ip/DAC_Driver/DAC_Driver_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAC_Driver'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.gen/sources_1/ip/DAC_Driver/DAC_Driver.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAC_Driver'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
