# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.srcs/sources_1/ip/fir_filter_q/fir_filter_q.xci
# IP: The module: 'fir_filter_q' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.gen/sources_1/ip/fir_filter_q/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_q'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.gen/sources_1/ip/fir_filter_q/fir_filter_q_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_q'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.srcs/sources_1/ip/fir_filter_q/fir_filter_q.xci
# IP: The module: 'fir_filter_q' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.gen/sources_1/ip/fir_filter_q/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_q'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Alex/Documents/GitHub/impedance-analyzer/Vivado Project/impedance_analyzer/impedance_analyzer.gen/sources_1/ip/fir_filter_q/fir_filter_q_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_q'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
